  services:
    springapp:
      build: .
      container_name: springapp
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uniroom
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      ports:
        - 8000:8080
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=uniroom
        - PGDATA=/home/postgresql/data/pgdata
      ports:
        - 5001:5432
      restart: always
      volumes:
        - pgdata:/home/postgresql/data
  volumes:
    pgdata:
